name: spring server ci cd

on:
  push:
    branches: ["feature/docker-compose"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: update submodules
        run: git submodule update --remote

      - name: 자바 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: 빌드
        run: ./gradlew build

      - name: 도커 이미지 빌드
        run: docker build -t ${{ secrets.DOCKER_IMG }} .

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_IMG }}

      - name: 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker rm -f $(docker ps -qa)
            docker rmi $(docker images -q)
            docker volume prune
            docker volume rm $(docker volume ls -q)
            docker pull ${{ secrets.DOCKER_IMG }}
            docker run -v /var/run/docker.sock:/var/run/docker.sock -v ${{ github.workspace }}:/app -w /app docker/compose:1.29.0 up -d -f /app/docker-compose.yml
  
